### ISSUE TITLE
New versions of Firebug are not detected

### ISSUE THREAD

**Issue by rensatsu** [sindresorhus/devtools-detect#16]
It seems that new versions of Firebug doesn't modify 'window' object with 'Firebug', so it's useless to check for 'window.Firebug'. It instead adds new function called 'window.console.exception' which can be used for detection.

**Comment by sindresorhus** [comment]
It will still detect Firebug when it's docked. Also `window.console.exception` seems to be available even when Firebug is not open though, so can't really use that. Other suggestions welcome :)
