### ISSUE TITLE
How do you import this using browserify?

### ISSUE THREAD

**Issue by mabasic** [sindresorhus/devtools-detect#18]
After installing it using NPM, I could not do 

```
import devtools from "devtools-detect";
```

or

```
var devtools = require('devtools-detect');
```

I had to install using Bower and then copy the `devtools-detect.js` file to `/libs` directory and then using browserify I could do:

```
import devtools from './libs/devtools-detect.js';
```

And then it worked.

Am I doing something wrong?

**Comment by sindresorhus** [comment]
Sorry about that. I apparently forgot to set the `main` reference in package.json. Fixed now.

**Comment by mabasic** [comment]
Thank you very much.
