### ISSUE TITLE
if inspect opened on undock into separate window, this event not working

### ISSUE THREAD

**Issue by pavhov** [sindresorhus/devtools-detect#32]
if inspect opened on **undock into separate window**, _this event not working_
![image](https://user-images.githubusercontent.com/8784893/33499289-cfcd2dd2-d6ed-11e7-8d5c-ca5be0061cf5.png)

**Comment by sindresorhus** [comment]
That's documented:

> Caveats
> Doesn't work if DevTools is undocked and will show false positive if you toggle any kind of sidebar.

**Comment by pavhov** [comment]
Okay, 
Sorry for late answer
