### ISSUE TITLE
False negative on page load

### ISSUE THREAD

**Issue by emattias** [sindresorhus/devtools-detect#37]
When I load the page with devtools open I get this result:

```js
import devtoolsDetect from 'devtools-detect';

console.log(devtoolsDetect.isOpen) // false
```

I think its because the code if delayed by [500ms](https://github.com/sindresorhus/devtools-detect/blob/master/index.js#L50).

Could we maybe make the first run be run immediately or add an event for when the devtools detection code has actually been run?

**Comment by sindresorhus** [comment]
> Could we maybe make the first run be run immediately

👍
