### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/devtools-detect#5]
Create some examples on how it can be useful.

Ideas:
- Pause canvas when devtools is open
- Add style info inline
- ?

**Comment by cheapsteak** [comment]
Online game (e.g. cookie clicker), devtools open -> potential cheating

**Comment by arthurvr** [comment]
> Online game (e.g. cookie clicker), devtools open -> potential cheating

We shouldn't suggest that kind of usage IMHO. This utility is a funny thing and can be handy for debugging purposes, but has many caveats and isn't reliable.
