### ISSUE TITLE
Pure Javascript

### ISSUE THREAD

**Issue by Noido** [sindresorhus/devtools-detect#51]
Hi, can you convert your code in Pure Javascript plz ?

Cause i don t have node and can t install 

Thank you

**Comment by bgbruno** [comment]
it is pure js

if it doesn't work for you for any reason - try rem these lines
`// 	if (typeof module !== 'undefined' && module.exports) {`
`// 		module.exports = devtools;`
`// 	} else {`
`		window.devtools = devtools;`
`// 	}`

and let this line do that work
`		window.devtools = devtools;`

then you can  use for eg
`window.devtools.isOpen`

**Comment by Noido** [comment]
Ok thanks
