### ISSUE TITLE
False positive when download bar is open

### ISSUE THREAD

**Issue by thomaspark** [sindresorhus/devtools-detect#52]
First of all, thanks for such a handy utility.

I noticed that when the download bar is open, devtools is incorrectly reported as open. See screenshot:

<img width="1111" alt="Screen Shot 2021-11-22 at 11 23 59 AM" src="https://user-images.githubusercontent.com/900407/142897948-ce759ca8-c993-4ae3-a967-ee86f73d53a8.png">

**Comment by andresOlarte** [comment]
Hi, 
I have confirmed this problem on a website of mine. I have had to remove devtools-detect because my users often download items from my website and this behavior turns out to be a big problem as they end up seeing a 404 after every download.

**Comment by CatchLF** [comment]
> First of all, thanks for such a handy utility.
> 
> I noticed that when the download bar is open, devtools is incorrectly reported as open. See screenshot:
> 
> <img alt="Screen Shot 2021-11-22 at 11 23 59 AM" width="1111" src="https://user-images.githubusercontent.com/900407/142897948-ce759ca8-c993-4ae3-a967-ee86f73d53a8.png">

I think I may have found a solution.
You can refer to this issues:https://github.com/sindresorhus/devtools-detect/issues/2#issue-16467493
