### ISSUE TITLE
(Chrome) DevTools not detected while device toolbar 

### ISSUE THREAD

**Issue by thedtvn** [sindresorhus/devtools-detect#55]
![image](https://user-images.githubusercontent.com/80153297/152684599-d9d45513-089a-4038-b746-ec564467ff7f.png)

**Comment by brndto** [comment]
not too sure what you mean by device toolbar. the devtools is known as "undocked" when it is in it's own separate window.

**Comment by Directory** [comment]
and this is a known caveat. not a bug
